version: '3'

services:
  node0:
    container_name: node0
    image: "tendermint/localnode"
    command: ["node", "--proxy_app", "tcp://192.167.11.2:26658", "kvstore", "--consensus.create_empty_blocks=false"]
    ports:
      - "26656-26657:26656-26657"
    environment:
      - ID=0
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.2

  node1:
    container_name: node1
    image: "tendermint/localnode"
    command: ["node", "--proxy_app", "tcp://192.167.11.3:26658", "kvstore", "--consensus.create_empty_blocks=false"]
    ports:
      - "26658-26659:26656-26657"
    environment:
      - ID=1
      - LOG=${LOG:-tendermint.log}
    volumes:
      - ./build:/tendermint:Z
    networks:
      localnet:
        ipv4_address: 192.167.10.3

  app0:
    container_name: app0
    image: "eddsatendermintserver_server"
    depends_on:
        - node0
        - node1
    command: ["/target/release/server", "--address", "192.167.11.2:26658"]
    ports:
      - "36656:26658"
    networks:
      localnet:
        ipv4_address: 192.167.11.2

  app1:
    container_name: app1
    image: "eddsatendermintserver_server"
    depends_on:
        - node0
        - node1
    command: ["/target/release/server", "--address", "192.167.11.3:26658"]
    ports:
      - "36657:26658"
    networks:
      localnet:
        ipv4_address: 192.167.11.3

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.167.10.0/16


